name: Update Hyperliquid Stats Data

on:
  schedule:
    # Run every 1 hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install node-fetch@2
          
      - name: Run volume and OI data fetch script
        run: |
          node js/fetch_volume_OI.js
          
      - name: Run stats data fetch script
        run: |
          node js/stats.js
          
      - name: Run assistance fund data fetch script
        run: |
          node js/afdata.js
          
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/volume_data.json data/open_interest_data.json data/fee_data.json data/tvl_data.json data/assistance_fund_data.json
          git diff --staged --quiet || git commit -m "Update Hyperliquid stats data [automated]"
          git push
