name: Update Blog Index

on:
  push:
    branches:
      - main
    paths:
      - 'blog/markdown/**'
  pull_request:
    branches:
      - main
    paths:
      - 'blog/markdown/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install gray-matter slugify
        
      - name: Run index generator
        run: node scripts/new-post.js
        
      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git diff --exit-code --quiet blog/markdown/index.json; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add blog/markdown/index.json
          git commit -m "Update blog index.json [automated]"
          git push
