name: Update Blog Index

on:
  push:
    branches:
      - main
    paths:
      - 'blog/markdown/**'
  pull_request:
    branches:
      - main
    paths:
      - 'blog/markdown/**'
  workflow_dispatch:  # Allows manual triggering

# Set the permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # No need to specify token here as we're using the default GITHUB_TOKEN
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install gray-matter slugify
        
      - name: Run index generator
        run: node scripts/new-post.js
        
      - name: Commit and push changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git diff --exit-code --quiet blog/markdown/index.json; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add blog/markdown/index.json
          git commit -m "Update blog index.json [automated]"
          
          # Pull changes first to avoid conflicts
          git pull --rebase origin main
          
          # Push using the GITHUB_TOKEN
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
