name: Update Volume and OI Data

on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          cd hype4
          npm install node-fetch
          
      - name: Run data fetch script
        run: |
          cd hype4
          node js/fetch_volume_OI.js
          
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add hype4/data/volume_data.json hype4/data/open_interest_data.json
          git diff --staged --quiet || git commit -m "Update volume and OI data [automated]"
          git push
